"Notifier-ProcessRedButton.st
Make the red button act like the yellow one within a notifier.

    AUTHOR          Stephen T. Pope (stp@create.ucsb.edu)
    VERSION         1.0
    PREREQUISITES   none
    DISTRIBUTION    world
    VERSION ID      1
    VERSION DATE    November 7, 1996"!


!NotifyStringHolderController methodsFor: 'editing'!
processRedButton
	"Bring up the menu here."

	self processYellowButton! !