"Preferences-userPlacement.st
User places windows on open.

    AUTHOR          Stephen T. Pope (stp@create.ucsb.edu)
    VERSION         1.0
    PREREQUISITES   none
    DISTRIBUTION    world
    VERSION ID      1
    VERSION DATE    November 19, 1996"!


!Preferences class methodsFor: 'ui prefs'!
userPlacement
	"Answer whether the user prefers to place and size all new windows by hand."

	^true! !